name: 'aws-run'
description: 'Runs a shellscript inside of an AWS VPC'
author: 'Jonathan Nagayoshi'
inputs:
  role_arn:
    required: true
    description: Role ARN to be used to create/execute the required infrastructure on AWS
  execution_role_arn:
    required: false
    description: Role ARN to be used to as execution role for the ECS Task that will run the script. Defaults to ROLE_ARN
  task_role_arn:
    required: false
    description: Role ARN to be used as Task Role arn for the ECS Task that will run the script. Defaults to ROLE_ARN
  memory:
    required: false
    default: "512"
    description: Amount of memory to be used by the remote ECS Task (Must be a FARGATE Compatible combination. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
  cpu:
    required: false
    default: "256"
    description: Amount of vCPU to be used by the remote ECS Task (Must be a FARGATE Compatible combination. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
  ecs_cluster_name:
    required: false
    default: "github-actions-aws-run"
    description: The name of the ECS Cluster where the Tasks will run. It will be automatically created if it doesn't exist
  image:
    required: true
    description: Name of the docker container to be used for the step execution
  region:
    required: true
    description: AWS Region to execute the operations
    default: us-east-1
  security_group_id:
    required: false
    description: Security Group to be used by the ECS Task. If not informed, a temporary security group will be created with access to the internet
  run:
    required: true
    description: Script that will be executed in the remote environment
  shell:
    required: true
    description: Name of the shell to be used in the container to execute the run script
  subnet_ids:
    required: true
    description: Subnet ID of where the Task will be executed.
  vpc_id:
    required: true
    description: VPC ID of where the Task will be executed
  
runs:
  using: 'node16'
  main: 'dist/index.js'
