name: aws-run
description: Runs a remote workload inside of an AWS VPC using ECS Fargate Tasks
author: Jonathan Nagayoshi
inputs:
  role_arn:
    required: true
    description: Role ARN to be used to create/execute the required infrastructure on AWS
  execution_role_arn:
    required: false
    description: Role ARN to be used to as execution role for the ECS Task that will run the script. Defaults to ROLE_ARN
  task_role_arn:
    required: false
    description: Role ARN to be used as Task Role arn for the ECS Task that will run the script. Defaults to ROLE_ARN
  memory:
    required: false
    default: "512"
    description: Amount of memory to be used by the remote ECS Task (Must be a FARGATE Compatible combination. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
  cpu:
    required: false
    default: "256"
    description: Amount of vCPU to be used by the remote ECS Task (Must be a FARGATE Compatible combination. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
  ecs_cluster_name:
    required: false
    default: "github-actions-aws-run"
    description: The name of the ECS Cluster where the Tasks will run. It will be automatically created if it doesn't exist
  image:
    required: true
    description: Name of the docker container to be used for the step execution
  region:
    required: true
    description: AWS Region to execute the operations
    default: us-east-1
  security_group_id:
    required: false
    description: Security Group to be used by the ECS Task. If not informed, a temporary security group will be created with access to the internet
  run:
    required: true
    description: Script that will be executed in the remote environment
  shell:
    required: true
    description: Name of the shell to be used in the container to execute the run script
  subnet_ids:
    required: false
    description: Subnet ID of where the Task will be executed. If no subnet_ids is specified, the task will find one automatically within the VPC
  vpc_id:
    required: true
    description: VPC ID of where the Task will be executed
  tags:
    required: false
    description: A multiline string in the format of KEY=VALUE of custom tags to be added to all resources created on AWS
  polling_interval:
    required: false
    default: 2
    description: The amount of time (in seconds) between polling cloudwatch logs.
  post_complete_log_cycles:
    required: false
    default: 4
    description: Number of polling cycles to try getting logs after the ecs task completes.
  upload_includes:
    required: false
    description: Array of string paths to include while uploading the runner workspace to the ECS Task. Excludes apply before includes. See https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters
  upload_excludes:
    required: false
    description: Array of string paths to exclude while uploading the runner workspace to the ECS Task. Excludes apply before includes. See https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters
  download_includes:
    required: false
    description: Array of string paths to include while downloading the runner workspace from the ECS Task. Excludes apply before includes. See https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters
  download_excludes:
    required: false
    description: Array of string paths to exclude while downloading the runner workspace from the ECS Task. Excludes apply before includes. See https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
