name: 'aws-run'
description: 'Runs a shellscript inside of an AWS VPC'
author: 'Jonathan Nagayoshi'
inputs:
  role_arn:
    required: true
    description: 'Role ARN to be used to create/execute the required infrastructure on AWS'
  image:
    required: true
    description: Name of the docker container to be used for the step execution
  
runs:
  using: 'node16'
  main: 'dist/index.js'
